"""
SYNC_REPORT.md generator for forksync.

Produces a human-readable markdown report of every sync run,
committed to the repo so it's visible on GitHub.
"""

import logging
from datetime import datetime, timezone
from typing import Dict, List, Optional

from forksync import ForkStatus, SyncResult, SyncState

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """\
# Fork Sync Report
**{username}'s GitHub Forks** · {date} · {duration}

---

## Summary
| Status | Count |
|--------|-------|
| ✅ Synced | {synced_count} |
| ⏭️ Already current | {current_count} |
| ⚠️ Needs attention | {conflict_count} |
| 🗄️ Archived (skipped) | {archived_count} |
| ⬆️ Ahead (skipped) | {ahead_count} |

**API calls used**: {api_calls} / 5,000 hourly limit

---

## ✅ Synced ({synced_count} repos)

| Repo | Commits merged | Upstream |
|------|----------------|----------|
{synced_table}

---

## ⚠️ Needs Manual Attention ({conflict_count} repos)

These forks have diverged from upstream. GitHub Issues created for each.

| Repo | Ahead by | Behind by | Issue |
|------|----------|-----------|-------|
{conflict_table}

---

## ⬆️ Skipped — Local Changes ({ahead_count} repos)

These forks have commits not in upstream. Skipped to preserve your changes.

{ahead_list}

---

*Generated by [forksync](https://github.com/perditioinc/forksync)*
*Next run: tomorrow at 6am UTC*
"""


def _format_duration(seconds: float) -> str:
    """Format duration as human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"


class ReportGenerator:
    """
    Generates SYNC_REPORT.md from sync run results.
    """

    def generate(
        self,
        results: List[SyncResult],
        statuses: Dict[str, ForkStatus],
        username: str,
        duration: float,
        api_calls: int,
    ) -> str:
        """
        Generate the full SYNC_REPORT.md content.

        Args:
            results: List of SyncResult from the engine.
            statuses: Dict of repo_name -> ForkStatus.
            username: GitHub username.
            duration: Total run duration in seconds.
            api_calls: Total API calls made.

        Returns:
            Markdown string ready to write to SYNC_REPORT.md.
        """
        now = datetime.now(timezone.utc)
        date_str = now.strftime("%Y-%m-%d %H:%M UTC")
        duration_str = _format_duration(duration)

        # Categorize results
        synced = [r for r in results if r.action_taken == "synced"]
        conflicts = [r for r in results if r.action_taken == "conflict_reported"]
        dry_runs = [r for r in results if r.action_taken == "dry_run"]

        # Count categories from statuses/results
        synced_count = len(synced) + len(dry_runs)  # dry_run shows what would sync
        conflict_count = len(conflicts)

        current_count = sum(
            1
            for r in results
            if r.action_taken == "skipped"
            and r.state == SyncState.UP_TO_DATE
        )
        archived_count = sum(
            1
            for r in results
            if r.action_taken == "skipped"
            and (r.state == SyncState.ARCHIVED)
        )
        ahead_count = sum(
            1
            for r in results
            if r.action_taken == "skipped"
            and r.state == SyncState.AHEAD
        )

        # Build synced table
        synced_rows = []
        for result in synced + dry_runs:
            status = statuses.get(result.repo_name)
            if status:
                upstream_link = f"[{status.upstream_repo}]({status.upstream_url})"
                fork_link = f"[{result.repo_name}]({status.fork_url})"
                dry_marker = " *(dry run)*" if result.action_taken == "dry_run" else ""
                synced_rows.append(
                    f"| {fork_link} | {result.commits_merged}{dry_marker} | {upstream_link} |"
                )
            else:
                synced_rows.append(
                    f"| {result.repo_name} | {result.commits_merged} | — |"
                )

        if not synced_rows:
            synced_rows.append("| — | — | — |")

        synced_table = "\n".join(synced_rows)

        # Build conflict table
        conflict_rows = []
        for result in conflicts:
            status = statuses.get(result.repo_name)
            if status:
                fork_link = f"[{result.repo_name}]({status.fork_url})"
                issue_link = (
                    f"[Issue]({result.issue_url})" if result.issue_url else "—"
                )
                conflict_rows.append(
                    f"| {fork_link} | {status.ahead_by} | {status.behind_by} | {issue_link} |"
                )
            else:
                issue_link = f"[Issue]({result.issue_url})" if result.issue_url else "—"
                conflict_rows.append(
                    f"| {result.repo_name} | — | — | {issue_link} |"
                )

        if not conflict_rows:
            conflict_rows.append("| — | — | — | — |")

        conflict_table = "\n".join(conflict_rows)

        # Build ahead list
        ahead_results = [
            r
            for r in results
            if r.action_taken == "skipped" and r.state == SyncState.AHEAD
        ]
        ahead_lines = []
        for result in ahead_results:
            status = statuses.get(result.repo_name)
            if status:
                ahead_lines.append(
                    f"- [{result.repo_name}]({status.fork_url}) "
                    f"— {status.ahead_by} commit(s) ahead of "
                    f"[{status.upstream_repo}]({status.upstream_url})"
                )
            else:
                ahead_lines.append(f"- {result.repo_name}")

        if not ahead_lines:
            ahead_list = "*None*"
        else:
            ahead_list = "\n".join(ahead_lines)

        return REPORT_TEMPLATE.format(
            username=username,
            date=date_str,
            duration=duration_str,
            synced_count=synced_count,
            current_count=current_count,
            conflict_count=conflict_count,
            archived_count=archived_count,
            ahead_count=ahead_count,
            api_calls=api_calls,
            synced_table=synced_table,
            conflict_table=conflict_table,
            ahead_list=ahead_list,
        )

    def write(self, content: str, path: str = "SYNC_REPORT.md") -> None:
        """Write the report to disk."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("SYNC_REPORT.md written to %s", path)
